# escape=`
FROM microsoft/iis:nanoserver-sac2016 

COPY .\docker\frontend-reverse-proxy\homepage\img\ C:\inetpub\wwwroot\img\
COPY .\docker\frontend-reverse-proxy\homepage\index.html C:\inetpub\wwwroot